<p>1.) Write a function so that the columns of the output matrix are powers of the input
vector.</p>
<p>The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.</p>
<p>HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile
Vandermonde.</p>


In [14]:
#Import numpy
import numpy as np

#Define function
def vandermatrix(inp_array,in_dim):
    return np.vander(inp_array,in_dim)
#define array    
ar=[]    
#Take array input from user
while(True):
    elm=input("Enter the array element or STOP to exit :")
    if(elm == 'STOP'):
        break
    else:
        ar.append(int(elm))
#Take Matrix dimension from user        
dim =int(input("Enter the dimension : "))        
result=vandermatrix(ar,dim)
#Print result
print("The Resultant Matrix is : ")
print(result)


Enter the array element or STOP to exit :1
Enter the array element or STOP to exit :2
Enter the array element or STOP to exit :3
Enter the array element or STOP to exit :STOP
Enter the dimension : 3
The Resultant Matrix is : 
[[1 1 1]
 [4 2 1]
 [9 3 1]]


In [ ]:
3